#string methods muttable
name = "utkarsh!!!! mohit !!!!piyush !!!!aniket!!!!"
print(name.upper())
print(name.lower())
print(len(name[0]))
print(name.capitalize())
print(name.title())
print(name.rstrip("!"))
print(name.find("m"))
print(name.index("m"))
print(name.isalnum())
print(name.isprintable())
print(name.replace("utkarsh", "anisha"))
print(name.split(""" """))
topic = "python ia an interpreted language and it is used for web development, data science, machine learning and many more."
print(topic.swapcase())
print(topic.title())
print(len(name[0:5]))
print((name.find("t")))
print(name.replace("t", "T"))
